### ISSUE TITLE
Plugin isn't working

### ISSUE THREAD

**Issue by Fonzee9** [Rexcantor/MultiLanguagePlugin#13]
I set my language to Portuguese to test it and everything is still in english for me??

**Comment by Rexcantor** [comment]
The plugin is not an auto-translator. As stated on the plugin page under "Description":

> Do you own an international server? Want to have it in different languages, per player? You're lucky then! MultiLanguagePlugin (MLP) is here with a lot of cool features! This plugin uses a placeholder which will be replaced (dynamically, per player) with a message **defined in the language file**. More info below.

You must add your own messages and they will be automatically replaced. Check the documentation for more information.

**Comment by Fonzee9** [comment]
How about in chat when people type?

**Comment by Rexcantor** [comment]
That's not the propose of the plugin. Also, that's already on my upcoming feature list, although it may not be so good, because if you think, it would add a lot of delay to the message, because it would have to go to a translating service and come back.

The propose of the plugin is to give the ability to send plugin messages like "Player1 was killed by Player2", "You have been healed", etc in multiple languages.

**Comment by Fonzee9** [comment]
It was the purpose of why i bought it for $9 i thought everything changes to whatever language they speak.

**Comment by Fonzee9** [comment]
This plugin is almost like i never added it i can go on another language and it doesn't translate i am upset.

**Comment by Fonzee9** [comment]
I am never gonna use this plugin i bought it to translate chat messages and it doesn't do what i bought it to do so i am not happy i am removing this from my server and i want my money back because this is ridiculous.

**Comment by Rexcantor** [comment]
I'll solve this with you tomorrow. It's 00:18 for me and I need to sleep.

**Comment by Rexcantor** [comment]
Please add me on Discord so we can discuss the issue privately: `Rexcantor64#7413`
